name: Generate Windows EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build EXE File
        run: flutter build windows --release

      - name: Upload EXE Package
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-Windows-App
          path: build/
